name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Python ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        include:
          - {version: '3.6', os: ubuntu-latest}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
            auto-update-conda: true
            environment-file: dev_env.yml
            activate-environment: test-env
            python-version: ${{ matrix.version }}
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Run tests
        run: |
          python setup.py install
          pytest
